### ISSUE TITLE
helm charts: hardcoded dockerhub `postgres:14`

### ISSUE THREAD

**Issue by sgatewood-da** [digital-asset/decentralized-canton-sync#122]
For multiple charts we use a postgres init container:

```yaml
      initContainers:
        - name: {{ .Release.Name }}-init-sequencer
          image: postgres:14
```

We probably want to allow specifying your `.Values.imageRepo`
